	AREA RESET,DATA,READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,= SRC
	MOV R3, #10
UP
	LDR R1,[R0],#4
	ADDS R2,R1
	ADC R5,#0
	SUBS R3,#1
	BNE UP
	LDR R4,= Result
	STR R2,[R4],#4
	STR R5,[R4]
STOP
	B STOP
SRC DCD 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
	AREA mydata,DATA,READWRITE
Result DCD 0
	END